Repository in2code-de/femanager, pull requests merged in 2021-05, with the labels that each got.

#339 [BUGFIX] Select previously saved state in state menu
  Classes/ViewHelpers/Form/SelectViewHelper.php
  Resources/Private/JavaScript/Femanager.js
  Resources/Public/JavaScript/Backend.min.js
  Resources/Public/JavaScript/Femanager.min.js
  composer.json
Labels: status: in review

#261 [BUGFIX] return true for FileReferences
  Classes/Domain/Validator/ServersideValidator.php
Labels: type: bug

#333 Migration Breaking: #92609 v11.0
  ext_localconf.php
Labels: status: in review

#253 Update AbstractValidator.php
  Classes/Domain/Validator/AbstractValidator.php
Labels: status: in review, type: bug
