Repository in2code-de/femanager, pull requests merged in 2021-09, with the labels that each got.

#392 Add setter to allow modification of email object inside event listeners
  Classes/Event/BeforeMailSendEvent.php
Labels: type: feature, status: resolved

#393 Fix embedded images in emails
  Classes/Domain/Service/SendMailService.php
Labels: type: bug

#394 [BUGFIX] add missing field mapping for custom properties for TYPO3v10+
  Documentation/Features/NewFields/Index.rst
Labels: type: documentation
